#!/usr/bin/env python
import os
import rospy
import rospkg
from std_msgs.msg import String

TOPIC = 'identify'

def callback(data):
    rospack = rospkg.RosPack()
    path = rospack.get_path('master')
    opts = rospy.get_param('~alsa_opts', '')
    os.system(f'aplay {opts} {path}/assets/identify.wav')
    
def listener():
    rospy.init_node('identify', anonymous=True)
    rospy.Subscriber(TOPIC, String, callback)
    rospy.loginfo('Starting identify server')
    rospy.spin()

if __name__ == '__main__':
    listener()
